In [1]:
import pandas as pd
import numpy as np
data = [[110,120,110],[130,130,130],[130,120,130]]
columns = ["语文","数学","英语"]
df= pd.DataFrame(data=data,columns=columns)
print(df.median(axis='index'))

语文    130.0
数学    120.0
英语    130.0
dtype: float64

In [2]:
df = pd.DataFrame(np.random.random([5,5]),columns=['A1','A2','A3','A4','A5'])
df

         A1        A2        A3        A4        A5
0  0.173023  0.197595  0.643206  0.499330  0.102913
1  0.619339  0.649423  0.053478  0.806786  0.155676
2  0.664114  0.109009  0.467597  0.554604  0.686101
3  0.834573  0.953598  0.851019  0.988010  0.356682
4  0.811140  0.846294  0.926317  0.814912  0.442903

In [10]:
df['A1'].apply(lambda x:"{:.2%}".format(x))

0    35.32%
1    68.12%
2    24.99%
3    52.40%
4    45.83%
Name: A1, dtype: object

In [12]:
data = [["零基础学Python","1月",49768889],["零基础学Python","2月",11777775],["零基础学Python","3月",13799990]]
columns = ["图书","月份","码洋"]
df= pd.DataFrame(data=data,columns=columns)
df

           图书  月份        码洋
0  零基础学Python  1月  49768889
1  零基础学Python  2月  11777775
2  零基础学Python  3月  13799990

In [13]:
df['码洋'] = df['码洋'].apply(lambda x:"{:,}".format(x))
df

           图书  月份          码洋
0  零基础学Python  1月  49,768,889
1  零基础学Python  2月  11,777,775
2  零基础学Python  3月  13,799,990

In [15]:
df = pd.read_csv("./data/JD.csv",encoding='gbk')
df

                         商品名称        一级分类          二级分类  7天点击量     定价  订单预定
0        ASP.NET项目开发实战入门（全彩版）   编程语言与程序设计       ASP.NET     35   69.8     1
1            PHP项目开发实战入门（全彩版）   编程语言与程序设计           PHP     49   69.8     0
2           Java精彩编程200例（全彩版）   编程语言与程序设计          Java     51   79.8     2
3                零基础学PHP（全彩版）   编程语言与程序设计           PHP     64   79.8     1
4            JSP项目开发实战入门（全彩版）   编程语言与程序设计   JSP/JavaWeb     26   69.8     0
5             C#精彩编程200例（全彩版）   编程语言与程序设计            C#     60   89.8     1
6                零基础学C语言（全彩版）   编程语言与程序设计       C++/C语言    227   69.8    11
7         零基础学JavaScript（全彩版）  网页制作/Web技术    JavaScript    100   79.8     7
8             C#项目开发实战入门（全彩版）   编程语言与程序设计            C#    122   69.8     3
9            C语言项目开发实战入门（全彩版）   编程语言与程序设计       C++/C语言    111   59.8     5
10           零基础学Android（全彩版）        移动开发       Android     85   89.8     4
11               零基础学C++（全彩版）   编程语言与程序设计       C++/C语言    165   79.8     5
12       JavaWeb项目开发实战入门（全彩版）   编程语言与程序设计   JSP/JavaWeb    131   69.8     1
13              零基础学Java（全彩版）   编程语言与程序设计          Java    149   69.8    10
14        零基础学HTML5+CSS3（全彩版）  网页制作/Web技术          HTML    188   79.8     8
15            零基础学Python（全彩版）   编程语言与程序设计        Python   1139   79.8    79
16              Java开发详解（全彩版）   编程语言与程序设计          Java    125  119.0     1
17            案例学WEB前端开发（全彩版）  网页制作/Web技术         WEB前端     57   49.8     0
18           C++项目开发实战入门（全彩版）   编程语言与程序设计       C++/C语言    149   69.8     4
19       Android精彩编程200例（全彩版）        移动开发       Android     32   89.8     1
20           零基础学ASP.NET（全彩版）   编程语言与程序设计       ASP.NET     52   79.8     1
21        Python从入门到项目实践（全彩版）   编程语言与程序设计        Python    597   99.8    25
22        Python项目开发案例集锦（全彩版）   编程语言与程序设计        Python    474  128.0    15
23          Java项目开发实战入门（全彩版）   编程语言与程序设计          Java     83   59.8     3
24       Android项目开发实战入门（全彩版）        移动开发       Android     85   59.8     2
25            零基础学Oracle（全彩版）         数据库        Oracle     58   79.8     2
26                零基础学C#（全彩版）   编程语言与程序设计            C#    132   79.8     8
27               SQL即查即用（全彩版）         数据库           SQL    128   49.8    13
28           Android开发详解（全彩版）        移动开发       Android     59  119.0     0
29             玩转C语言程序设计（全彩版）   编程语言与程序设计       C++/C语言     27   49.8     2
30            Python编程锦囊（全彩版）   编程语言与程序设计        Python    239   79.8    13
31           C语言精彩编程200例（全彩版）   编程语言与程序设计       C++/C语言     45   79.8     1
32  Visual Basic精彩编程200例（全彩版）   编程语言与程序设计  Visual Basic     28   79.8     0

In [18]:
df1=df[['一级分类','7天点击量','订单预定']]
for name,group in df1.groupby('一级分类'): 
    print(name) 
    print(group)
    print(type(group))

数据库
   一级分类  7天点击量  订单预定
25  数据库     58     2
27  数据库    128    13
<class 'pandas.core.frame.DataFrame'>
移动开发
    一级分类  7天点击量  订单预定
10  移动开发     85     4
19  移动开发     32     1
24  移动开发     85     2
28  移动开发     59     0
<class 'pandas.core.frame.DataFrame'>
编程语言与程序设计
         一级分类  7天点击量  订单预定
0   编程语言与程序设计     35     1
1   编程语言与程序设计     49     0
2   编程语言与程序设计     51     2
3   编程语言与程序设计     64     1
4   编程语言与程序设计     26     0
5   编程语言与程序设计     60     1
6   编程语言与程序设计    227    11
8   编程语言与程序设计    122     3
9   编程语言与程序设计    111     5
11  编程语言与程序设计    165     5
12  编程语言与程序设计    131     1
13  编程语言与程序设计    149    10
15  编程语言与程序设计   1139    79
16  编程语言与程序设计    125     1
18  编程语言与程序设计    149     4
20  编程语言与程序设计     52     1
21  编程语言与程序设计    597    25
22  编程语言与程序设计    474    15
23  编程语言与程序设计     83     3
26  编程语言与程序设计    132     8
29  编程语言与程序设计     27     2
30  编程语言与程序设计    239    13
31  编程语言与程序设计     45     1
32  编程语言与程序设计     28     0
<class 'pandas.core.frame.DataFrame'>
网页制作/Web技术
          一级分类  7天点击量  订单预定
7   网页制作/Web技术    100     7
14  网页制作/Web技术    188     8
17  网页制作/Web技术     57     0
<class 'pandas.core.frame.DataFrame'>

In [19]:
df2 = df[['一级分类','二级分类','7天点击量','订单预定']]
for (key1,key2),group in df2.groupby(['一级分类','二级分类']): 
    print(key1,key2)
    print(group)

数据库 Oracle
   一级分类    二级分类  7天点击量  订单预定
25  数据库  Oracle     58     2
数据库 SQL
   一级分类 二级分类  7天点击量  订单预定
27  数据库  SQL    128    13
移动开发 Android
    一级分类     二级分类  7天点击量  订单预定
10  移动开发  Android     85     4
19  移动开发  Android     32     1
24  移动开发  Android     85     2
28  移动开发  Android     59     0
编程语言与程序设计 ASP.NET
         一级分类     二级分类  7天点击量  订单预定
0   编程语言与程序设计  ASP.NET     35     1
20  编程语言与程序设计  ASP.NET     52     1
编程语言与程序设计 C#
         一级分类 二级分类  7天点击量  订单预定
5   编程语言与程序设计   C#     60     1
8   编程语言与程序设计   C#    122     3
26  编程语言与程序设计   C#    132     8
编程语言与程序设计 C++/C语言
         一级分类     二级分类  7天点击量  订单预定
6   编程语言与程序设计  C++/C语言    227    11
9   编程语言与程序设计  C++/C语言    111     5
11  编程语言与程序设计  C++/C语言    165     5
18  编程语言与程序设计  C++/C语言    149     4
29  编程语言与程序设计  C++/C语言     27     2
31  编程语言与程序设计  C++/C语言     45     1
编程语言与程序设计 JSP/JavaWeb
         一级分类         二级分类  7天点击量  订单预定
4   编程语言与程序设计  JSP/JavaWeb     26     0
12  编程语言与程序设计  JSP/JavaWeb    131     1
编程语言与程序设计 Java
         一级分类  二级分类  7天点击量  订单预定
2   编程语言与程序设计  Java     51     2
13  编程语言与程序设计  Java    149    10
16  编程语言与程序设计  Java    125     1
23  编程语言与程序设计  Java     83     3
编程语言与程序设计 PHP
        一级分类 二级分类  7天点击量  订单预定
1  编程语言与程序设计  PHP     49     0
3  编程语言与程序设计  PHP     64     1
编程语言与程序设计 Python
         一级分类    二级分类  7天点击量  订单预定
15  编程语言与程序设计  Python   1139    79
21  编程语言与程序设计  Python    597    25
22  编程语言与程序设计  Python    474    15
30  编程语言与程序设计  Python    239    13
编程语言与程序设计 Visual Basic
         一级分类          二级分类  7天点击量  订单预定
32  编程语言与程序设计  Visual Basic     28     0
网页制作/Web技术 HTML
          一级分类  二级分类  7天点击量  订单预定
14  网页制作/Web技术  HTML    188     8
网页制作/Web技术 JavaScript
         一级分类        二级分类  7天点击量  订单预定
7  网页制作/Web技术  JavaScript    100     7
网页制作/Web技术 WEB前端
          一级分类   二级分类  7天点击量  订单预定
17  网页制作/Web技术  WEB前端     57     0

In [21]:
df1.groupby("一级分类").agg(['mean','sum'])

                 7天点击量        订单预定
                  mean   sum  mean  sum
一级分类
数据库          93.000000   186  7.50   15
移动开发         65.250000   261  1.75    7
编程语言与程序设计   178.333333  4280  8.00  192
网页制作/Web技术  115.000000   345  5.00   15

In [22]:
df1.groupby("一级分类").agg({"7天点击量":"sum","订单预定":["mean","sum"]})

           7天点击量  订单预定
             sum  mean  sum
一级分类
数据库          186  7.50   15
移动开发         261  1.75    7
编程语言与程序设计   4280  8.00  192
网页制作/Web技术   345  5.00   15

In [31]:
df = pd.read_excel("./data/1月01.xlsx")
df

     买家会员名  买家实际支付金额 收货人姓名             宝贝标题  数量
0    mrhy1     41.86   周某某       零基础学Python   1
1    mrhy2     41.86   杨某某       零基础学Python   1
2    mrhy3     48.86   刘某某       零基础学Python   1
3    mrhy4     48.86   张某某       零基础学Python   1
4    mrhy5     48.86   赵某某       C#项目开发实战入门   1
5    mrhy6     48.86   李某某       C#项目开发实战入门   1
6    mrhy7    104.72   张某某      C语言精彩编程200例   3
7    mrhy8     55.86   周某某      C语言精彩编程200例   1
8    mrhy9     79.80   李某某      C语言精彩编程200例   1
9   mrhy10     29.90   程某某      C语言项目开发实战入门   1
10  mrhy11     41.86   曹某某      C语言项目开发实战入门   1
11  mrhy12     41.86   陈某某      C语言项目开发实战入门   1
12  mrhy13     41.86   郝某某      C语言项目开发实战入门   1
13  mrhy14     41.86   胡某某      C语言项目开发实战入门   1
14  mrhy15     41.86   孙某某      C语言项目开发实战入门   1
15  mrhy16     41.86   余某某      C语言项目开发实战入门   1
16  mrhy17     48.86   郭某某  JavaWeb项目开发实战入门   1
17  mrhy18     48.86   阿某某  JavaWeb项目开发实战入门   1
18  mrhy19     48.86   高某某  JavaWeb项目开发实战入门   1
19  mrhy20     48.86   许某某       零基础学Python   1
20  mrhy21     48.86   陈某某       零基础学Python   1
21  mrhy22     48.86   张某某       零基础学Python   1
22  mrhy23     97.72   李某某     Java精彩编程200例   2
23  mrhy24     41.86   素某某     Java项目开发实战入门   1
24  mrhy25     41.86   闫某某     Java项目开发实战入门   1
25  mrhy26     41.86   陈某某     Java项目开发实战入门   1
26  mrhy27     48.86   刘某某      JSP项目开发实战入门   1
27  mrhy28     48.86   高某某      JSP项目开发实战入门   1
28  mrhy29     34.86   孟某某          SQL即查即用   1
29  mrhy30     34.86   郑某某          SQL即查即用   1
30  mrhy31     34.86   熊某某          SQL即查即用   1
31  mrhy32     90.72   严某某          SQL即查即用   1
32  mrhy33     46.86   胡某某       零基础学Python   1
33  mrhy34     46.86   额某某       零基础学Python   1
34  mrhy35     46.86   许某某       零基础学Python   1
35  mrhy36     46.86   陈某某       零基础学Python   1
36  mrhy37     46.86   刘某某       零基础学Python   1
37  mrhy38     62.86   方某某      零基础学Android   1
38  mrhy39     62.86   张某某      零基础学Android   1
39  mrhy40     55.86   毛某某           零基础学C#   1
40  mrhy41     55.86   林某某           零基础学C#   1
41  mrhy42     55.86   李某某           零基础学C#   1
42  mrhy43     48.86   晏某某          零基础学C语言   1
43  mrhy44     48.86   程某某          零基础学C语言   1
44  mrhy45     48.86   杨某某       零基础学Python   1
45  mrhy46     48.86   张某某       零基础学Python   1
46  mrhy47     48.86   王某某       零基础学Python   1
47  mrhy48     48.86   王某某       零基础学Python   1
48  mrhy49     48.86   高某某       零基础学Python   1
49  mrhy50     48.86   李某某       零基础学Python   1

In [30]:
df.agg({["数量":['sum','mean'],"买家实际支付金额":['sum','mean']})

SyntaxError: invalid syntax (3976556985.py, line 1)

In [26]:
# 创建示例数据
data = {
   'department': ['HR', 'Tech', 'HR', 'Tech'],
        'salary': [6000, 8000, 7000, 9000],
        'experience': [3, 5, 4, 6]}
df = pd.DataFrame(data)

# 定义自定义聚合函数
def custom_agg(series):
    return series.max() - series.min()

# 按部门分组并应用自定义聚合函数
custom_agg_result = df.groupby('department')['salary'].agg(custom_agg)
print("按部门分组并应用自定义聚合函数：")
print(custom_agg_result)

按部门分组并应用自定义聚合函数：
department
HR      1000
Tech    1000
Name: salary, dtype: int64

## 通过字典进行分组统计，把北京、上海、广州三个城市放在一起统计

In [41]:
df = pd.read_csv("./data/JD01.csv",encoding='gbk')
df.set_index("商品名称",inplace=True)
dict1 = {"北京出库销量":"北上广","上海出库销量":"北上广","广州出库销量":"北上广","成都出库销量":"成都","武汉出库销量":"武汉"}
df1 = df.groupby(dict1,axis='columns').sum()
df1

                      北上广   成都   武汉
商品名称
零基础学Python（全彩版）      1991  284  246
Python从入门到项目实践（全彩版）   798  113   92
Python项目开发案例集锦（全彩版）   640  115   88
Python编程锦囊（全彩版）       457   85   65
零基础学C语言（全彩版）          364   82   63
SQL即查即用（全彩版）          305   29   25
零基础学Java（全彩版）         238   48   43
零基础学C++（全彩版）          223   53   35
零基础学C#（全彩版）           146   27   16
C#项目开发实战入门（全彩版）       135   18   22

## 通过Serie对象进行分组统计，把北京、上海、广州三个城市放在一起统计

In [42]:
data = {"北京出库销量":"北上广","上海出库销量":"北上广","广州出库销量":"北上广","成都出库销量":"成都","武汉出库销量":"武汉"}
s1 = pd.Series(data)
print(s1)

北京出库销量    北上广
上海出库销量    北上广
广州出库销量    北上广
成都出库销量     成都
武汉出库销量     武汉
dtype: object

In [44]:
df1 = df.groupby(s1,axis='columns').sum()
df1

                      北上广   成都   武汉
商品名称
零基础学Python（全彩版）      1991  284  246
Python从入门到项目实践（全彩版）   798  113   92
Python项目开发案例集锦（全彩版）   640  115   88
Python编程锦囊（全彩版）       457   85   65
零基础学C语言（全彩版）          364   82   63
SQL即查即用（全彩版）          305   29   25
零基础学Java（全彩版）         238   48   43
零基础学C++（全彩版）          223   53   35
零基础学C#（全彩版）           146   27   16
C#项目开发实战入门（全彩版）       135   18   22

## 计算和上一次的升降

In [47]:
data = [110,105,125,137,116]
index = [1,2,3,4,5]

df3 = pd.DataFrame(data,index=index,columns=['语文'])
df3['和上次升降'] = df3 - df3.shift()
df3

    语文  和上次升降
1  110    NaN
2  105   -5.0
3  125   20.0
4  137   12.0
5  116  -21.0

## 分隔较长的数据

In [3]:
df = pd.read_excel("./data/mrbooks.xls",usecols=['买家会员名','收货地址'])
df

       买家会员名                              收货地址
0    mr00001                       重庆 重庆市 南岸区
1    mr00003          江苏省 苏州市 吴江区 吴江经济技术开发区亨通路
2    mr00004  江苏省 苏州市 园区 苏州市工业园区唯亭镇阳澄湖大道维纳阳光花园
3    mr00002      重庆 重庆市 南岸区 长生桥镇茶园新区长电路11112号
4    mr00005          安徽省 滁州市 明光市 三界镇中心街10001号
..       ...                               ...
193  mr00232              陕西省 咸阳市 三原县 城关街道林履大街
194  mr00234              湖北省 武汉市 洪山区 和平街道绿景苑.
195  mr00235              江苏省 南京市 玄武区 孝陵卫街道孝陵卫
196  mr00236              河南省 驻马店市 汝南县 和孝镇和孝第一
197  mr00237              陕西省 西安市 未央区 张家堡街道凤城六

[198 rows x 2 columns]

In [9]:
series = df['收货地址'].str.split(" ",expand=True) #expand=True：分割结果自动转换为DataFrame
df['省'] = series[0]
df['市'] = series[1]
df['区'] = series[2]
df

       买家会员名                              收货地址    省     市    区
0    mr00001                       重庆 重庆市 南岸区    重庆   重庆市  南岸区
1    mr00003          江苏省 苏州市 吴江区 吴江经济技术开发区亨通路  江苏省   苏州市  吴江区
2    mr00004  江苏省 苏州市 园区 苏州市工业园区唯亭镇阳澄湖大道维纳阳光花园  江苏省   苏州市   园区
3    mr00002      重庆 重庆市 南岸区 长生桥镇茶园新区长电路11112号   重庆   重庆市  南岸区
4    mr00005          安徽省 滁州市 明光市 三界镇中心街10001号  安徽省   滁州市  明光市
..       ...                               ...  ...   ...  ...
193  mr00232              陕西省 咸阳市 三原县 城关街道林履大街  陕西省   咸阳市  三原县
194  mr00234              湖北省 武汉市 洪山区 和平街道绿景苑.  湖北省   武汉市  洪山区
195  mr00235              江苏省 南京市 玄武区 孝陵卫街道孝陵卫  江苏省   南京市  玄武区
196  mr00236              河南省 驻马店市 汝南县 和孝镇和孝第一  河南省  驻马店市  汝南县
197  mr00237              陕西省 西安市 未央区 张家堡街道凤城六  陕西省   西安市  未央区

[198 rows x 5 columns]

In [10]:
df = pd.read_excel("./data/mrbooks.xls",usecols=['买家会员名','宝贝标题'])

In [11]:
df

       买家会员名                                               宝贝标题
0    mr00001                                        PHP程序员开发资源库
1    mr00003                                          个人版编程词典加点
2    mr00004                                                 邮费
3    mr00002  零基础学Java全彩版 ，Java精彩编程200例，Java项目开发实战入门全彩版，Java...
4    mr00005                                         零基础学PHP全彩版
..       ...                                                ...
193  mr00232                                   明日科技 Java编程词典个人版
194  mr00234                                            零基础学C语言
195  mr00235                                       Java精彩编程200例
196  mr00236                                        C语言精彩编程200例
197  mr00237                                         C#学习黄金组合套装

[198 rows x 2 columns]

In [14]:
df.join(df['宝贝标题'].str.split("，",expand=True))

,买家会员名,宝贝标题,0,1,2,3
0,mr00001,PHP程序员开发资源库,PHP程序员开发资源库,None,None,None
1,mr00003,个人版编程词典加点,个人版编程词典加点,None,None,None
2,mr00004,邮费,邮费,None,None,None
3,mr00002,零基础学Java全彩版 ，Java精彩编程200例，Java项目开发实战入门全彩版，Java...,零基础学Java全彩版,Java精彩编程200例,Java项目开发实战入门全彩版,Java编程词典个人版
4,mr00005,零基础学PHP全彩版,零基础学PHP全彩版,None,None,None
...,...,...,...,...,...,...
193,mr00232,明日科技 Java编程词典个人版,明日科技 Java编程词典个人版,None,None,None
194,mr00234,零基础学C语言,零基础学C语言,None,None,None
195,mr00235,Java精彩编程200例,Java精彩编程200例,None,None,None
196,mr00236,C语言精彩编程200例,C语言精彩编程200例,None,None,None
197,mr00237,C#学习黄金组合套装,C#学习黄金组合套装,None,None,None

In [17]:
pd.concat([df,df['宝贝标题'].str.split("，",expand=True)],axis='columns')

,买家会员名,宝贝标题,0,1,2,3
0,mr00001,PHP程序员开发资源库,PHP程序员开发资源库,None,None,None
1,mr00003,个人版编程词典加点,个人版编程词典加点,None,None,None
2,mr00004,邮费,邮费,None,None,None
3,mr00002,零基础学Java全彩版 ，Java精彩编程200例，Java项目开发实战入门全彩版，Java...,零基础学Java全彩版,Java精彩编程200例,Java项目开发实战入门全彩版,Java编程词典个人版
4,mr00005,零基础学PHP全彩版,零基础学PHP全彩版,None,None,None
...,...,...,...,...,...,...
193,mr00232,明日科技 Java编程词典个人版,明日科技 Java编程词典个人版,None,None,None
194,mr00234,零基础学C语言,零基础学C语言,None,None,None
195,mr00235,Java精彩编程200例,Java精彩编程200例,None,None,None
196,mr00236,C语言精彩编程200例,C语言精彩编程200例,None,None,None
197,mr00237,C#学习黄金组合套装,C#学习黄金组合套装,None,None,None

## 将DataFrame中的元组类型数据分隔成多列

In [21]:
df = pd.DataFrame({'a':[1,2,3,4,5],'b':[(1,2),(3,4),(5,6),(7,8),(9,10)]})
df

   a        b
0  1   (1, 2)
1  2   (3, 4)
2  3   (5, 6)
3  4   (7, 8)
4  5  (9, 10)

In [22]:
df['b'].apply(pd.Series)

   0   1
0  1   2
1  3   4
2  5   6
3  7   8
4  9  10

In [27]:
df[["b1","b2"]] = df['b'].apply(pd.Series) #或者df.join(df['b'].apply(pd.Series))

In [28]:
df

   a        b  b1  b2
0  1   (1, 2)   1   2
1  2   (3, 4)   3   4
2  3   (5, 6)   5   6
3  4   (7, 8)   7   8
4  5  (9, 10)   9  10

In [29]:
df.join(df['b'].apply(pd.Series))

   a        b  b1  b2  0   1
0  1   (1, 2)   1   2  1   2
1  2   (3, 4)   3   4  3   4
2  3   (5, 6)   5   6  5   6
3  4   (7, 8)   7   8  7   8
4  5  (9, 10)   9  10  9  10

## pivot()方法进行数据重排

In [4]:
df = pd.read_excel("./data/grade.xls",sheet_name='英语3')
df

    序号  班级   姓名  得分   排名
0    1  1班  王*亮  84   11
1    2  1班  杨**  82   17
2    3  1班  王*彬  78   37
3    1  2班  赛*琪  77   51
4    2  2班  刘**  76   64
5    3  2班  刘*彤  74   89
6    1  3班  张*扬  72  115
7    2  3班  尹**  72  115
8    3  3班  李*旸  72  115
9    1  4班  *华煦  72  115
10   2  4班  于*明  72  115
11   3  4班  袁*皓  70  151
12   1  5班   姜*  70  151
13   2  5班  窦**  68  195
14   3  5班  张*昕  68  195

In [5]:
df1 = df.pivot(index='序号',columns='班级',values='得分')
df1

班级  1班  2班  3班  4班  5班
序号
1   84  77  72  72  70
2   82  76  72  72  68
3   78  74  72  70  68

In [6]:
df.pivot_table(index='序号',columns='班级',values='得分')

班级  1班  2班  3班  4班  5班
序号
1   84  77  72  72  70
2   82  76  72  72  68
3   78  74  72  70  68

In [9]:
df = pd.read_excel("./data/mrbooks.xls")
df1 = df.groupby("宝贝标题")['宝贝总数量'].sum().head()
mydict = df1.to_dict()
for i,j in df1.items(): 
    print(i,':\t',j)

ASP.NET项目开发实战入门全彩版 :	 32
ASP.NET项目开发实战入门全彩版，ASP.NET全能速查宝典 :	 2
Android学习黄金组合套装 :	 4
Android项目开发实战入门 :	 1
C#+ASP.NET项目开发实战入门全彩版 :	 1

In [10]:
mydict

{'ASP.NET项目开发实战入门全彩版': 32,
 'ASP.NET项目开发实战入门全彩版，ASP.NET全能速查宝典': 2,
 'Android学习黄金组合套装': 4,
 'Android项目开发实战入门': 1,
 'C#+ASP.NET项目开发实战入门全彩版': 1}

In [11]:
df = pd.read_excel("./data/TB2018.xls")
df

   买家会员名  买家实际支付金额  宝贝总数量                宝贝标题    类别              订单付款时间
0  mr001    143.50    2.0           Python黄金组合   图书 2018-10-09 22:54:26
1  mr002     78.80    1.0           Python编程锦囊  NaN 2018-10-09 22:52:42
2  mr003     48.86    1.0              零基础学C语言   图书 2018-01-19 12:53:01
3  mr004     81.75    NaN  SQL Server应用与开发范例宝典   图书 2018-06-30 11:46:14
4  mr005    299.00    1.0        Python程序开发资源库  NaN 2018-03-23 18:25:45
5  mr006     41.86    1.0           零基础学Python   图书 2018-03-24 19:25:45
6  mr007     55.86    1.0          C语言精彩编程200例   图书 2018-03-25 11:00:45
7  mr008     41.86    NaN          C语言项目开发实战入门   图书 2018-03-26 23:11:11
8  mr009     41.86    1.0         Java项目开发实战入门   图书 2018-03-27 07:25:30
9  mr010     34.86    1.0              SQL即查即用   图书 2018-03-28 18:09:12

## 修改时间序列

In [15]:
df.set_index("订单付款时间").resample("AS").sum().to_period("A")

,买家会员名,买家实际支付金额,宝贝总数量,宝贝标题,类别
订单付款时间,,,,,
2018,mr003mr005mr006mr007mr008mr009mr010mr004mr002m...,868.21,9.0,零基础学C语言Python程序开发资源库零基础学PythonC语言精彩编程200例C语言项目...,图书图书图书图书图书图书图书图书

In [18]:
df.set_index("订单付款时间").resample("Q").sum().to_period("Q")

,买家会员名,买家实际支付金额,宝贝总数量,宝贝标题,类别
订单付款时间,,,,,
2018Q1,mr003mr005mr006mr007mr008mr009mr010,564.16,6.0,零基础学C语言Python程序开发资源库零基础学PythonC语言精彩编程200例C语言项目...,图书图书图书图书图书图书
2018Q2,mr004,81.75,0.0,SQL Server应用与开发范例宝典,图书
2018Q3,0,0.00,0.0,0,0
2018Q4,mr002mr001,222.30,3.0,Python编程锦囊Python黄金组合,图书

In [20]:
rng = pd.date_range('2/2/2020',periods=12,freq="T")
s1 = pd.Series(np.arange(12),index=rng)
s1

2020-02-02 00:00:00     0
2020-02-02 00:01:00     1
2020-02-02 00:02:00     2
2020-02-02 00:03:00     3
2020-02-02 00:04:00     4
2020-02-02 00:05:00     5
2020-02-02 00:06:00     6
2020-02-02 00:07:00     7
2020-02-02 00:08:00     8
2020-02-02 00:09:00     9
2020-02-02 00:10:00    10
2020-02-02 00:11:00    11
Freq: T, dtype: int32

In [22]:
s1.resample("5min").ohlc()

                     open  high  low  close
2020-02-02 00:00:00     0     4    0      4
2020-02-02 00:05:00     5     9    5      9
2020-02-02 00:10:00    10    11   10     11